%-------------
% Interval Tab
%-------------

% Auto Detect Range Button
btnAutoDetection.ButtonPushedFcn = {@autoDetection_callback, axPre, ...
    axInter, listInterRngMax, efLowLimRngMax, efHighLimRngMax, ...
    listInterRngMdd, efLowLimRngMdd, efHighLimRngMdd, ...
    listInterRngMin, efLowLimRngMin, efHighLimRngMin, ...
    sThresholdMin, sThresholdMdd, sThresholdMax, btnReadyIntervals, 0, ...
    btnDelInterRngMax, btnEditInterRngMax, btnNewInterRngMax, ...
    btnDelInterRngMdd, btnEditInterRngMdd, btnNewInterRngMdd, ...
    btnDelInterRngMin, btnEditInterRngMin, btnNewInterRngMin, ...
    btnExportIntervals, btnDetectionSettings};

% Detection Settings
btnDetectionSettings.ButtonPushedFcn = {@detectionSettings_callback};

% Detect Button
% Max
btnDetectionMax.ButtonPushedFcn = {@detection_callback, axPre, ...
    axInter, listInterRngMax, efLowLimRngMax, efHighLimRngMax, ...
    sThresholdMax, btnReadyIntervals, 1, ...
    btnDelInterRngMax, btnEditInterRngMax, btnNewInterRngMax, ...
    btnDetectionSettings};
% Mid
btnDetectionMdd.ButtonPushedFcn = {@detection_callback, axPre, ...
    axInter, listInterRngMdd, efLowLimRngMdd, efHighLimRngMdd, ...
    sThresholdMdd, btnReadyIntervals, 1, ...
    btnDelInterRngMdd, btnEditInterRngMdd, btnNewInterRngMdd, ...
    btnDetectionSettings};
% Min
btnDetectionMin.ButtonPushedFcn = {@detection_callback, axPre, ...
    axInter, listInterRngMin, efLowLimRngMin, efHighLimRngMin, ...
    sThresholdMin, btnReadyIntervals, 1, ...
    btnDelInterRngMin, btnEditInterRngMin, btnNewInterRngMin, ...
    btnDetectionSettings};

% Interval's List
% Max
listInterRngMax.ValueChangedFcn = {@listInterval_callback, axInter, ...
    efLowLimRngMax, efHighLimRngMax};
% Mid
listInterRngMdd.ValueChangedFcn = {@listInterval_callback, axInter, ...
    efLowLimRngMdd, efHighLimRngMdd};
% Min
listInterRngMin.ValueChangedFcn = {@listInterval_callback, axInter, ...
    efLowLimRngMin, efHighLimRngMin};

% Edit Interval Button
% Max
btnEditInterRngMax.ButtonPushedFcn = {@editInterval_callback, axPre, ...
    listInterRngMax, axInter, efLowLimRngMax, efHighLimRngMax};
% Mid
btnEditInterRngMdd.ButtonPushedFcn = {@editInterval_callback, axPre, ...
    listInterRngMdd, axInter, efLowLimRngMdd, efHighLimRngMdd};
% Min
btnEditInterRngMin.ButtonPushedFcn = {@editInterval_callback, axPre, ...
    listInterRngMin, axInter, efLowLimRngMin, efHighLimRngMin};

% Delete Interval Button
% Max
btnDelInterRngMax.ButtonPushedFcn = {@deleteInterval_callback, ...
    listInterRngMax, axInter, efLowLimRngMax, efHighLimRngMax, ...
    uitDeletedMax};
% Mid
btnDelInterRngMdd.ButtonPushedFcn = {@deleteInterval_callback, ...
    listInterRngMdd, axInter, efLowLimRngMdd, efHighLimRngMdd, ...
    uitDeletedMdd};
% Min
btnDelInterRngMin.ButtonPushedFcn = {@deleteInterval_callback, ...
    listInterRngMin, axInter, efLowLimRngMin, efHighLimRngMin, ...
    uitDeletedMin};

% New Interval Button
% Max
btnNewInterRngMax.ButtonPushedFcn = {@newInterval_callback, ...
    listInterRngMax, axInter, efLowLimRngMax, efHighLimRngMax, ...
    uitAddedMax};
% Mid
btnNewInterRngMdd.ButtonPushedFcn = {@newInterval_callback, ...
    listInterRngMdd, axInter, efLowLimRngMdd, efHighLimRngMdd, ...
    uitAddedMdd};
% Min
btnNewInterRngMin.ButtonPushedFcn = {@newInterval_callback, ...
    listInterRngMin, axInter, efLowLimRngMin, efHighLimRngMin, ...
    uitAddedMin};

% Zoom Region Button
% Max
btnZoomInterRngMax.ButtonPushedFcn = {@zoomRegion_callback, ...
    axInter, axPre, btnReadyIntervals};
% Mid
btnZoomInterRngMdd.ButtonPushedFcn = {@zoomRegion_callback, ...
    axInter, axPre, btnReadyIntervals};
% Min
btnZoomInterRngMin.ButtonPushedFcn = {@zoomRegion_callback, ...
    axInter, axPre, btnReadyIntervals};

% General View Button
btnGeneralView.ButtonPushedFcn = {@generalView_callback, axInter};

% Change Bound Button
% Max
btnChangeMaxBound.ButtonPushedFcn = {@changeBound_callback, axPre, ...
    btnReadyIntervals, pRangeMax, pRangeMdd, pRangeMin};
% Mdd
btnChangeMddBound.ButtonPushedFcn = {@changeBound_callback, axPre, ...
    btnReadyIntervals, pRangeMax, pRangeMdd, pRangeMin};

% Ready Intervals Button
btnReadyIntervals.ButtonPushedFcn = {@readyIntervals_callback, axPre, ...
    tabMCR, btnMCRBuildMod, ...
    listInterRngMin, listInterRngMdd, listInterRngMax, ...
    listRegion1, listRegion2, listRegion3, tgRegions, tabRegion1, ...
    btnMCROaTinitialize, btnMCROaTsaveComp, rbPlotSVD, rbPlotInit, ...
    btnMCROaTBuildMod, axSTprofile, axCprofile, btnDelCompSelInter, ...
    btnMCROaTselInter, btnProceedToPCA, efLOfExp, ...
    axSegment, axSVDinit, sCompMCROaT, efLOfExVa, efLOfStdRes, ...
    btnExportModels};

% Export Intervals Button
btnExportIntervals.ButtonPushedFcn = {@exportIntervals_callback, ...
    axPre, listInterRngMin, listInterRngMdd, listInterRngMax};

%{
%%%%%% TEMPORAL %%%%%%%
btnImportSignals.ButtonPushedFcn = {@importSignals, efInterLimMin, ...
    efInterLimMax, axInter, listInterval, btnMCRBuildMod, btnReadyIntervals};
%}