%--------
% MCR-ALS Tab
%----------
% Initialize with nComp componentes Button
sCompMCROaT.ValueChangedFcn = {@actualizeComponents_callback, ...
    btnMCROaTinitialize};

% Save number of componentes Button
btnMCROaTsaveComp.ButtonPushedFcn = {@saveComponents_callback, ...
    tgRegions, tabMCR, listRegion1, listRegion2, listRegion3, ... 
    sCompMCROaT};

% Interval's List
listRegion1.ValueChangedFcn = {@listRegion_callback, tabMCR, ...
    axSegment, axSVDinit, axSTprofile, axCprofile,...
    sCompMCROaT, btnMCROaTinitialize, rbPlotSVD, ...
    efLOfExp, efLOfExVa, efLOfStdRes};
listRegion2.ValueChangedFcn = {@listRegion_callback, tabMCR, ...
    axSegment, axSVDinit, axSTprofile, axCprofile,...
    sCompMCROaT, btnMCROaTinitialize, rbPlotSVD, ...
    efLOfExp, efLOfExVa, efLOfStdRes};
listRegion3.ValueChangedFcn = {@listRegion_callback, tabMCR, ...
    axSegment, axSVDinit, axSTprofile, axCprofile,...
    sCompMCROaT, btnMCROaTinitialize, rbPlotSVD, ...
    efLOfExp, efLOfExVa, efLOfStdRes};

% Change Region Tab
tgRegions.SelectionChangedFcn = {@changeTab_callback, tabMCR, ...
    listRegion1, listRegion2, listRegion3, axSegment, axSVDinit, ...
    axSTprofile, axCprofile, ...
    btnMCROaTinitialize, sCompMCROaT, rbPlotSVD, efLOfExp, ...
    efLOfExVa, efLOfStdRes};

% Initialization with Purest ST
btnMCROaTinitialize.ButtonPushedFcn = {@initialization_callback, ...
    tabMCR, axSVDinit, tgRegions, ...
    listRegion1, listRegion2, listRegion3, rbPlotInit, sCompMCROaT};

% Select options in Plot Selection Purest ST
bgPlotSVDinit.SelectionChangedFcn = {@plotPurestST_callback, ...
    tabMCR, axSVDinit, tgRegions, listRegion1, listRegion2, listRegion3, ...
    sCompMCROaT, btnMCROaTinitialize};

% Build MCR-ALCS Model
% One-at-Time
btnMCROaTBuildMod.ButtonPushedFcn = {@buildMCRALSmodel_callback, ...
    tabMCR, [], sIterMCROaT, ...
    listRegion1, listRegion2, listRegion3, tgRegions,...
    axSVDinit, axSegment, axSTprofile, axCprofile, ...
    rbPlotSVD, efLOfExp, efLOfExVa, efLOfStdRes, ...
    btnMCROaTselInter, btnDelCompSelInter, btnProceedToPCA, ...
    btnExportModels};
% Only selected interval
btnMCROaTselInter.ButtonPushedFcn = {@buildModelSelectedInterval_callback, ...
    tgRegions, ...
    tabMCR, listRegion1, listRegion2, listRegion3, sIterMCROaT, ...
    axSTprofile, axCprofile, efLOfExp, efLOfExVa, ...
    efLOfStdRes};
% All-at-Once
btnMCRBuildMod.ButtonPushedFcn = {@buildMCRALSmodel_callback, ...
    tabMCR, sCompMCRAaO, sIterMCRAaO, ...
    listRegion1, listRegion2, listRegion3, tgRegions,...
    axSVDinit, axSegment, axSTprofile, axCprofile, ...
    rbPlotSVD, efLOfExp, efLOfExVa, efLOfStdRes, ...
    btnMCROaTselInter, btnDelCompSelInter, btnProceedToPCA, ...
    btnExportModels};

% Delete Components
btnDelCompSelInter.ButtonPushedFcn = {@deleteComponents_callback, ...
    tabMCR, tgRegions, listRegion1, listRegion2, listRegion3, ...
    axSTprofile, axCprofile};

% Proceed to Unsupervised Analysis
btnProceedToPCA.ButtonPushedFcn = {@proceedToPCA_callback, ...
    tabMCR, tabPCA, btnColorSamples, btnPCA, btnComparativePre, ...
    btnComparativePCA};

% Export Models Button
btnExportModels.ButtonPushedFcn = {@exportModels_callback, tabMCR};