%-------------
% Processing Tab
%-------------
% Import Data
btnImportData.ButtonPushedFcn = {@exploreFiles_callback,axRaw, ...
    ddVisualization, listSample, btnApplyVis, ...
    btnDeleteVis, btnEditVis, ...
    btnRange, btnAdd, btnIcoshift, btnBinning, btnDone, btnDelete, ...
    sFirstRange, sLastRange, sFirstPPM, sLastPPM, ...
    ddIcoshiftOption1, ddIcoshiftOption2, ddNormalization, ...
    sWidthBinning, btnRangeView, axPre, btnExportDataW, ...
    btnExportDataCSV, btnIntegration, btnIntegrationDataCSV, cbxPlot, ...
    btnBin2Com};
% Visualization Options "Visualization 1H-NMR Spectra"
ddVisualization.ValueChangedFcn = {@ddRawVisualization_callback, axRaw, ...
    btnApplyVis, btnDeleteVis, listSample};
% List Sample
listSample.ValueChangedFcn = {@listSample_callback, axRaw, btnApplyVis, ...
    btnDeleteVis, ddVisualization};
% Exclude Sample Button
btnDeleteVis.ButtonPushedFcn = {@btnDeleteVis_callback, listSample, ...
    btnApplyVis, btnImportData, ddVisualization};
% Apply Visualization Button
btnApplyVis.ButtonPushedFcn = {@applyVisualization_callback, ...
    ddNormalization, axPre, btnRange, btnIcoshift, btnBinning, ...
    btnDone, btnAdd, btnDelete, sFirstRange, sLastRange, ...
    sFirstPPM, sLastPPM, ddIcoshiftOption1, ddIcoshiftOption2, ...
    sWidthBinning, ...
    btnRangeView, btnApplyVis, btnExportDataW, btnExportDataCSV, ...
    btnImportData, btnDeleteVis, cbxPlot, btnBin2Com};
% Add Button
btnAdd.ButtonPushedFcn = {@viewOther_callback, ...
    sFirstPPM, sLastPPM, axPre};
% Delete Button
btnDelete.ButtonPushedFcn = {@deleteOther_callback, ...
    sFirstPPM, sLastPPM, axPre};
% Range Button
btnRange.ButtonPushedFcn = {@rangeOther_callback, ...
    sFirstRange, sLastRange, axPre};
%{
% Range automated Button
btnRangeAutomatic.ButtonPushedFcn = {@rangeOtherAutomated_callback, ...
    sFirstPPM, sLastPPM, axPre};
%}
% View Range Button
btnRangeView.ButtonPushedFcn = {@viewOtherRange_callback, ...
    sFirstRange, sLastRange, axPre};
% Normalization Options "Normalization 1H-NMR Spectra"
ddNormalization.ValueChangedFcn = {@ddCutNormalization_callback, axPre, ...
    btnComparativePre};
% Binning Button
btnBinning.ButtonPushedFcn = {@BinningOther_callback, ...
    sWidthBinning, axPre, btnIntegration, ddNormalization, ...
    btnBin2Com};
% Integration Button
btnIntegration.ButtonPushedFcn = {@integration_Callback, ...
    axPre, btnIntegrationDataCSV};
% Done Button
btnDone.ButtonPushedFcn = {@Done_callback, axInter, axPre, ...
    btnReadyIntervals, pRangeMax, pRangeMdd, pRangeMin, ...
    ddNormalization, ...
    btnAutoDetection, btnZoomInterRngMax, btnDetectionMax, ...
    btnZoomInterRngMdd, btnDetectionMdd, btnZoomInterRngMin, ...
    btnDetectionMin, btnChangeMaxBound, btnChangeMddBound, ...
    btnGeneralView, listInterRngMax, listInterRngMdd, listInterRngMin, ...
    btnDelInterRngMax, btnEditInterRngMax, btnNewInterRngMax, ...
    btnDelInterRngMdd, btnEditInterRngMdd, btnNewInterRngMdd, ...
    btnDelInterRngMin, btnEditInterRngMin, btnNewInterRngMin, ...
    btnExportIntervals, btnDetectionSettings};
% Binning to compare Button
btnBin2Com.ButtonPushedFcn = {@binning2compare_callback, ...
    sWidthBinning, axPre, btnComparativePre};
% Icoshift Button
btnIcoshift.ButtonPushedFcn = {@IcoshiftOther_callback, ...
    ddIcoshiftOption1, ddIcoshiftOption2, axPre};
% Export Data Workspace 
btnExportDataW.ButtonPushedFcn = {@exportDataW_callback, axPre};
% Export Data CSV
btnExportDataCSV.ButtonPushedFcn = {@exportDataCSV_callback, axPre};
% Export Integrated Data CSV
btnIntegrationDataCSV.ButtonPushedFcn = {@exportIntegratedDataCSV};
% Sync Plots
cbxPlot.ValueChangedFcn = {@cbxPlot_callback, axRaw, axPre, btnApplyVis};