%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Auto Detection Behaviour %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function autoDetection_callback(src, ~, axPre, axInter, ...
    listInterRngMax, efLowLimRngMax, efHighLimRngMax, ...
    listInterRngMdd, efLowLimRngMdd, efHighLimRngMdd, ...
    listInterRngMin, efLowLimRngMin, efHighLimRngMin, ...
    sThresholdMin, sThresholdMdd, sThresholdMax, btnReadyIntervals, ...
    OaT, btnDelInterRngMax, btnEditInterRngMax, btnNewInterRngMax, ...
    btnDelInterRngMdd, btnEditInterRngMdd, btnNewInterRngMdd, ...
    btnDelInterRngMin, btnEditInterRngMin, btnNewInterRngMin, ...
    btnExportIntervals, btnDetectionSettings)

% Loading window
fig = ancestor(src, 'figure', 'toplevel');
loadingWindow = uiprogressdlg(fig,'Title','Please Wait',...
        'Message','Detecting . . .', 'Indeterminate','on');

% Detection in Range Max
detection_callback(src, [], axPre, axInter, ...
    listInterRngMax, efLowLimRngMax, efHighLimRngMax, ...
    sThresholdMax, btnReadyIntervals, OaT, ...
    btnDelInterRngMax, btnEditInterRngMax, btnNewInterRngMax, ...
    btnDetectionSettings)

% Detection in Range Mid
detection_callback(src, [], axPre, axInter, ...
    listInterRngMdd, efLowLimRngMdd, efHighLimRngMdd, ...
    sThresholdMdd, btnReadyIntervals, OaT, ...
    btnDelInterRngMdd, btnEditInterRngMdd, btnNewInterRngMdd, ...
    btnDetectionSettings)

% Detection in Range Min
detection_callback(src, [], axPre, axInter, ...
    listInterRngMin, efLowLimRngMin, efHighLimRngMin, ...
    sThresholdMin, btnReadyIntervals, OaT, ...
    btnDelInterRngMin, btnEditInterRngMin, btnNewInterRngMin, ...
    btnDetectionSettings)

% Enable Export Button
btnExportIntervals.Enable = "on";

% Close loading windows and delete corresponding object
close(loadingWindow)
delete(loadingWindow)

end